ALTER TABLE users DROP CONSTRAINT IF EXISTS users_email_key;

ALTER TABLE users 
ADD COLUMN IF NOT EXISTS username VARCHAR(255) UNIQUE NOT NULL,
ADD COLUMN IF NOT EXISTS password VARCHAR(255) NOT NULL;
